
<script type="text/javascript">
    jQuery(document).ready(function () {
        //alert('fdsfdsfdsf maaanik');
        initMenu();
        //showUserName();
        //showApplicantName();
    });

    function initMenu() {
   
        jQuery("#smoothmenu1").empty();

        jQuery("#smoothmenu1").append(
        "<ul id='menu'>"
            +"<li><a href='<%=request.getContextPath()%>/'>Home</a></li>"+"<li><a href='#'>Root</a>"
            +"    <div class='dropdown_2columns'>"
            +"    <div class='col_1'>"
            +"    <ul>"
            +"        <li><a href='<%=request.getContextPath()%>/intgrtnAttnHo/list'>IntgrtnAttnHo</a></li>"
            +"        <li><a href='<%=request.getContextPath()%>/accTaxMst/list'>AccTaxMst</a></li>"
            +"        <li><a href='<%=request.getContextPath()%>/allLogo/list'>AllLogo</a></li>"
            +"        <li><a href='<%=request.getContextPath()%>/accTaxDtl/list'>AccTaxDtl</a></li>"
            +"        <li><a href='<%=request.getContextPath()%>/allOrg/list'>AllOrg</a></li>"
            +"        <li><a href='<%=request.getContextPath()%>/admFlexVal/list'>AdmFlexVal</a></li>"
            +"        <li><a href='<%=request.getContextPath()%>/accBnkAccntOrgLk/list'>AccBnkAccntOrgLk</a></li>"
            +"        <li><a href='<%=request.getContextPath()%>/admProp/list'>AdmProp</a></li>"
            +"        <li><a href='<%=request.getContextPath()%>/personEduDtl/list'>PersonEduDtl</a></li>"
            +"        <li><a href='<%=request.getContextPath()%>/accTaxMinZonal/list'>AccTaxMinZonal</a></li>"
            +"        <li><a href='<%=request.getContextPath()%>/accBnkAccnt/list'>AccBnkAccnt</a></li>"
            +"        <li><a href='<%=request.getContextPath()%>/allLoc/list'>AllLoc</a></li>"
            +"        <li><a href='<%=request.getContextPath()%>/accBnkBrnch/list'>AccBnkBrnch</a></li>"
            +"        <li><a href='<%=request.getContextPath()%>/accBnk/list'>AccBnk</a></li>"
            +"        <li><a href='<%=request.getContextPath()%>/person/list'>Person</a></li>"
            +"        <li><a href='<%=request.getContextPath()%>/allOrgMst/list'>AllOrgMst</a></li>"
            +"        <li><a href='<%=request.getContextPath()%>/alkp/list'>Alkp</a></li>"
            +"        <li><a href='<%=request.getContextPath()%>/accTaxPayTrnsc/list'>AccTaxPayTrnsc</a></li>"
            +"        <li><a href='<%=request.getContextPath()%>/intgrtnProp/list'>IntgrtnProp</a></li>"
            +"    </ul>"
            +"    </div>"
            +"    </div>"
            +"</li>"
            +"<li><a href='#'>Calc</a>"
            +"    <div class='dropdown_2columns'>"
            +"    <div class='col_1'>"
            +"    <ul>"
            +"        <li><a href='<%=request.getContextPath()%>/procTempDailyManPowerDtl/list'>ProcTempDailyManPowerDtl</a></li>"
            +"        <li><a href='<%=request.getContextPath()%>/procOutTlOtTrnsc/list'>ProcOutTlOtTrnsc</a></li>"
            +"        <li><a href='<%=request.getContextPath()%>/procOutAttnMst/list'>ProcOutAttnMst</a></li>"
            +"        <li><a href='<%=request.getContextPath()%>/procOutTlOtDtl/list'>ProcOutTlOtDtl</a></li>"
            +"        <li><a href='<%=request.getContextPath()%>/procOutPrlIncentive/list'>ProcOutPrlIncentive</a></li>"
            +"        <li><a href='<%=request.getContextPath()%>/procOutAprvlQueMst/list'>ProcOutAprvlQueMst</a></li>"
            +"        <li><a href='<%=request.getContextPath()%>/procOutTlRttn/list'>ProcOutTlRttn</a></li>"
            +"        <li><a href='<%=request.getContextPath()%>/procOutAprvlQueDtl/list'>ProcOutAprvlQueDtl</a></li>"
            +"        <li><a href='<%=request.getContextPath()%>/procOutTlShftTrnsc/list'>ProcOutTlShftTrnsc</a></li>"
            +"        <li><a href='<%=request.getContextPath()%>/procOutIrShortList/list'>ProcOutIrShortList</a></li>"
            +"        <li><a href='<%=request.getContextPath()%>/procOutRptQueDtl/list'>ProcOutRptQueDtl</a></li>"
            +"        <li><a href='<%=request.getContextPath()%>/procOutDtAttn/list'>ProcOutDtAttn</a></li>"
            +"        <li><a href='<%=request.getContextPath()%>/procOutTlDayTrnsc/list'>ProcOutTlDayTrnsc</a></li>"
            +"        <li><a href='<%=request.getContextPath()%>/procOutPrlDtl/list'>ProcOutPrlDtl</a></li>"
            +"        <li><a href='<%=request.getContextPath()%>/procSts/list'>ProcSts</a></li>"
            +"        <li><a href='<%=request.getContextPath()%>/procOutPrlMst/list'>ProcOutPrlMst</a></li>"
            +"        <li><a href='<%=request.getContextPath()%>/procOutPrlOt/list'>ProcOutPrlOt</a></li>"
            +"        <li><a href='<%=request.getContextPath()%>/procOutRptQueMst/list'>ProcOutRptQueMst</a></li>"
            +"        <li><a href='<%=request.getContextPath()%>/procOutPrlBonus/list'>ProcOutPrlBonus</a></li>"
            +"        <li><a href='<%=request.getContextPath()%>/procOutPrlAit/list'>ProcOutPrlAit</a></li>"
            +"        <li><a href='<%=request.getContextPath()%>/procOutTlOtReq/list'>ProcOutTlOtReq</a></li>"
            +"        <li><a href='<%=request.getContextPath()%>/procOutTemplate/list'>ProcOutTemplate</a></li>"
            +"        <li><a href='<%=request.getContextPath()%>/procOutPrlHold/list'>ProcOutPrlHold</a></li>"
            +"        <li><a href='<%=request.getContextPath()%>/procOutEvalMst/list'>ProcOutEvalMst</a></li>"
            +"        <li><a href='<%=request.getContextPath()%>/procOutTlOtMst/list'>ProcOutTlOtMst</a></li>"
            +"        <li><a href='<%=request.getContextPath()%>/procOutEvalDtl/list'>ProcOutEvalDtl</a></li>"
            +"        <li><a href='<%=request.getContextPath()%>/procOutLeaveYear/list'>ProcOutLeaveYear</a></li>"
            +"        <li><a href='<%=request.getContextPath()%>/procOutTlOffDayReq/list'>ProcOutTlOffDayReq</a></li>"
            +"    </ul>"
            +"    </div>"
            +"    </div>"
            +"</li>"
            +"<li><a href='#'>Com</a>"
            +"    <div class='dropdown_2columns'>"
            +"    <ul>"
            +"        <li><a href='<%=request.getContextPath()%>/admDynRptDtl/list'>AdmDynRptDtl</a></li>"
            +"        <li><a href='<%=request.getContextPath()%>/aclGrp/list'>AclGrp</a></li>"
            +"        <li><a href='<%=request.getContextPath()%>/admFrm/list'>AdmFrm</a></li>"
            +"        <li><a href='<%=request.getContextPath()%>/admDynRptMst/list'>AdmDynRptMst</a></li>"
            +"        <li><a href='<%=request.getContextPath()%>/admProcMst/list'>AdmProcMst</a></li>"
            +"        <li><a href='<%=request.getContextPath()%>/allCodeDef/list'>AllCodeDef</a></li>"
            +"        <li><a href='<%=request.getContextPath()%>/aclPrmssn/list'>AclPrmssn</a></li>"
            +"        <li><a href='<%=request.getContextPath()%>/admProcDtl/list'>AdmProcDtl</a></li>"
            +"        <li><a href='<%=request.getContextPath()%>/admAccessLog/list'>AdmAccessLog</a></li>"
            +"        <li><a href='<%=request.getContextPath()%>/aclUsr/list'>AclUsr</a></li>"
            +"        <li><a href='<%=request.getContextPath()%>/admRptDtl/list'>AdmRptDtl</a></li>"
            +"        <li><a href='<%=request.getContextPath()%>/admParam/list'>AdmParam</a></li>"
            +"        <li><a href='<%=request.getContextPath()%>/admRptMst/list'>AdmRptMst</a></li>"
            +"        <li><a href='<%=request.getContextPath()%>/aclUsrGrpLk/list'>AclUsrGrpLk</a></li>"
            +"    </ul>"
            +"    </div>"
            +"</li>"
            +"<li><a href='#'>fin</a>"
            +"    <div class='dropdown_2columns'>"
            +"    <div class='col_1'>"
            +"    <ul>"
            +"        <li><a href='<%=request.getContextPath()%>/accVoucherMst/list'>AccVoucherMst</a></li>"
            +"        <li><a href='<%=request.getContextPath()%>/accCurrencyRate/list'>AccCurrencyRate</a></li>"
            +"        <li><a href='<%=request.getContextPath()%>/accVoucherDtl/list'>AccVoucherDtl</a></li>"
            +"        <li><a href='<%=request.getContextPath()%>/accCoa/list'>AccCoa</a></li>"
            +"        <li><a href='<%=request.getContextPath()%>/accPeriod/list'>AccPeriod</a></li>"
            +"        <li><a href='<%=request.getContextPath()%>/accCostCntr/list'>AccCostCntr</a></li>"
            +"        <li><a href='<%=request.getContextPath()%>/accLedger/list'>AccLedger</a></li>"
            +"        <li><a href='<%=request.getContextPath()%>/accOpenningBalance/list'>AccOpenningBalance</a></li>"
            +"    </ul>"
            +"    </div>"
            +"    </div>"
            +"</li>"
            +"<li><a href='#'>com.aprvl</a>"
            +"    <div class='dropdown_2columns'>"
            +"    <div class='col_1'>"
            +"    <ul>"
            +"        <li><a href='<%=request.getContextPath()%>/admAprvlGrpDtl/list'>AdmAprvlGrpDtl</a></li>"
            +"        <li><a href='<%=request.getContextPath()%>/admAprvlHrchyMst/list'>AdmAprvlHrchyMst</a></li>"
            +"        <li><a href='<%=request.getContextPath()%>/admAprvlHrchyDtl/list'>AdmAprvlHrchyDtl</a></li>"
            +"        <li><a href='<%=request.getContextPath()%>/admAprvlGrpMst/list'>AdmAprvlGrpMst</a></li>"
            +"    </ul>"
            +"    </div>"
            +"    </div>"
            +"</li>"
            +"<li><a href='#'>com.msl</a>"
            +"    <div class='dropdown_2columns'>"
            +"    <div class='col_1'>"
            +"    <ul>"
            +"        <li><a href='<%=request.getContextPath()%>/admTemplateKeyword/list'>AdmTemplateKeyword</a></li>"
            +"        <li><a href='<%=request.getContextPath()%>/admMailService/list'>AdmMailService</a></li>"
            +"        <li><a href='<%=request.getContextPath()%>/admAcronym/list'>AdmAcronym</a></li>"
            +"        <li><a href='<%=request.getContextPath()%>/admTemplate/list'>AdmTemplate</a></li>"
            +"        <li><a href='<%=request.getContextPath()%>/admCrTarFinding/list'>AdmCrTarFinding</a></li>"
            +"    </ul>"
            +"    </div>"
            +"    </div>"
            +"</li>"
            +"<li><a href='#'>hcm.com</a>"
            +"    <div class='dropdown_2columns'>"
            +"    <div class='col_1'>"
            +"    <ul>"
            +"        <li><a href='<%=request.getContextPath()%>/hrCostCntr/list'>HrCostCntr</a></li>"
            +"    </ul>"
            +"    </div>"
            +"    </div>"
            +"</li>"
            +"<li><a href='#'>hcm.core</a>"
            +"    <div class='dropdown_2columns'>"
            +"    <div class='col_1'>"
            +"    <ul>"
            +"        <li><a href='<%=request.getContextPath()%>/hrCrDiscpTrnsc/list'>HrCrDiscpTrnsc</a></li>"
            +"        <li><a href='<%=request.getContextPath()%>/hrCrEmpAccnt/list'>HrCrEmpAccnt</a></li>"
            +"        <li><a href='<%=request.getContextPath()%>/hrCrOrganogram/list'>HrCrOrganogram</a></li>"
            +"        <li><a href='<%=request.getContextPath()%>/hrCrVcncyRqsn/list'>HrCrVcncyRqsn</a></li>"
            +"        <li><a href='<%=request.getContextPath()%>/hrCrSimRqsnDtl/list'>HrCrSimRqsnDtl</a></li>"
            +"        <li><a href='<%=request.getContextPath()%>/hrCrClrncMst/list'>HrCrClrncMst</a></li>"
            +"        <li><a href='<%=request.getContextPath()%>/hrCrEmpAddress/list'>HrCrEmpAddress</a></li>"
            +"        <li><a href='<%=request.getContextPath()%>/hrCrSimRqsnMst/list'>HrCrSimRqsnMst</a></li>"
            +"        <li><a href='<%=request.getContextPath()%>/hrCrPrsnalStmnt/list'>HrCrPrsnalStmnt</a></li>"
            +"        <li><a href='<%=request.getContextPath()%>/hrCrDiscp/list'>HrCrDiscp</a></li>"
            +"        <li><a href='<%=request.getContextPath()%>/hrCrEmpChildren/list'>HrCrEmpChildren</a></li>"
            +"        <li><a href='<%=request.getContextPath()%>/hrCrFire/list'>HrCrFire</a></li>"
            +"        <li><a href='<%=request.getContextPath()%>/hrCrEmpJobPrev/list'>HrCrEmpJobPrev</a></li>"
            +"        <li><a href='<%=request.getContextPath()%>/hrCrResign/list'>HrCrResign</a></li>"
            +"        <li><a href='<%=request.getContextPath()%>/hrCrIntrnshp/list'>HrCrIntrnshp</a></li>"
            +"        <li><a href='<%=request.getContextPath()%>/hrCrLoanMst/list'>HrCrLoanMst</a></li>"
            +"        <li><a href='<%=request.getContextPath()%>/hrCrClrncDtl/list'>HrCrClrncDtl</a></li>"
            +"        <li><a href='<%=request.getContextPath()%>/hrCrPrmtnDmtn/list'>HrCrPrmtnDmtn</a></li>"
            +"        <li><a href='<%=request.getContextPath()%>/hrCrClrncChklistDtl/list'>HrCrClrncChklistDtl</a></li>"
            +"        <li><a href='<%=request.getContextPath()%>/hrCrTour/list'>HrCrTour</a></li>"
            +"        <li><a href='<%=request.getContextPath()%>/hrCrEmpEdu/list'>HrCrEmpEdu</a></li>"
            +"        <li><a href='<%=request.getContextPath()%>/hrCrEmpLang/list'>HrCrEmpLang</a></li>"
            +"        <li><a href='<%=request.getContextPath()%>/hrCrDocRqsn/list'>HrCrDocRqsn</a></li>"
            +"        <li><a href='<%=request.getContextPath()%>/hrCrRejoin/list'>HrCrRejoin</a></li>"
            +"        <li><a href='<%=request.getContextPath()%>/hrCrLoanPayDtl/list'>HrCrLoanPayDtl</a></li>"
            +"        <li><a href='<%=request.getContextPath()%>/hrCrEmpDoc/list'>HrCrEmpDoc</a></li>"
            +"        <li><a href='<%=request.getContextPath()%>/hrCrPosn/list'>HrCrPosn</a></li>"
            +"        <li><a href='<%=request.getContextPath()%>/hrCrEmpSpclQlfctnLk/list'>HrCrEmpSpclQlfctnLk</a></li>"
            +"        <li><a href='<%=request.getContextPath()%>/hrCrYlwCrdDtl/list'>HrCrYlwCrdDtl</a></li>"
            +"        <li><a href='<%=request.getContextPath()%>/hrCrEmpContact/list'>HrCrEmpContact</a></li>"
            +"        <li><a href='<%=request.getContextPath()%>/hrCrEmpExt/list'>HrCrEmpExt</a></li>"
            +"        <li><a href='<%=request.getContextPath()%>/hrCrEmpPic/list'>HrCrEmpPic</a></li>"
            +"        <li><a href='<%=request.getContextPath()%>/hrCrLoanRecvDtl/list'>HrCrLoanRecvDtl</a></li>"
            +"        <li><a href='<%=request.getContextPath()%>/hrCrYlwCrdMst/list'>HrCrYlwCrdMst</a></li>"
            +"        <li><a href='<%=request.getContextPath()%>/hrCrInvRqsnDtl/list'>HrCrInvRqsnDtl</a></li>"
            +"        <li><a href='<%=request.getContextPath()%>/hrCrOffcCrclr/list'>HrCrOffcCrclr</a></li>"
            +"        <li><a href='<%=request.getContextPath()%>/hrCrAccdntl/list'>HrCrAccdntl</a></li>"
            +"        <li><a href='<%=request.getContextPath()%>/hrCrOffcLttr/list'>HrCrOffcLttr</a></li>"
            +"        <li><a href='<%=request.getContextPath()%>/hrCrEmpOwn/list'>HrCrEmpOwn</a></li>"
            +"        <li><a href='<%=request.getContextPath()%>/hrCrInvRqsnMst/list'>HrCrInvRqsnMst</a></li>"
            +"        <li><a href='<%=request.getContextPath()%>/hrCrEmpTraining/list'>HrCrEmpTraining</a></li>"
            +"        <li><a href='<%=request.getContextPath()%>/hrCrAssgnmnt/list'>HrCrAssgnmnt</a></li>"
            +"        <li><a href='<%=request.getContextPath()%>/hrCrEmpFamily/list'>HrCrEmpFamily</a></li>"
            +"        <li><a href='<%=request.getContextPath()%>/hrCrEmpCntctPrsn/list'>HrCrEmpCntctPrsn</a></li>"
            +"        <li><a href='<%=request.getContextPath()%>/hrCrEmpHlthMdctn/list'>HrCrEmpHlthMdctn</a></li>"
            +"        <li><a href='<%=request.getContextPath()%>/hrCrEmp/list'>HrCrEmp</a></li>"
            +"        <li><a href='<%=request.getContextPath()%>/hrCrIdCrdDstrbtn/list'>HrCrIdCrdDstrbtn</a></li>"
            +"    </ul>"
            +"    </div>"
            +"    </div>"
            +"</li>"
            +"<li><a href='<%=request.getContextPath()%>/logout' onclick='return confirm('Are you sure to Logout?');'><spring:message code='Logout'/></a></li>"
            +"</ul>"
    );

    }

</script>


<div class="bottom-header">

                      
                           <div id="smoothmenu1" class="ddsmoothmenu"></div>
                           <div class="clear"></div>
                     

                   </div>

<!--<div class="top-menu">
    <div id="smoothmenu1" class="ddsmoothmenu"></div>
    <div class="clear"></div>
</div>-->

